---
abstract: 'Check whether Perl files compile correctly.'
author:
  - 'Evan Giles <egiles@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Compile
provides:
  Test::Compile:
    file: lib/Test/Compile.pm
    version: 0.24
  Test::Compile::Internal:
    file: lib/Test/Compile/Internal.pm
    version: 0.24
recommends:
  Devel::CheckOS: 0
requires:
  UNIVERSAL::require: 0
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/egiles/test-compile
version: 0.24
