---
name: Test-Compile
version: 0.16
author:
  - 'Evan Giles <egiles@cpan.org>'
abstract: Check whether Perl module files compile correctly
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/egiles/test-compile
requires:
  UNIVERSAL::require: 0
  perl: v5.6.0
recommends:
  Devel::CheckOS: 0
configure_requires:
  Module::Build: 0.340201
provides:
  Test::Compile:
    file: lib/Test/Compile.pm
    version: 0.16
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
